### ISSUE TITLE
Cannot edit event information after creating

### ISSUE THREAD

**Issue by JoshuaCrewe** [tchapi/davis#73] opened 2022-08-18 09:39 UTC
I am testing on Apple Calendar and I am not sure what is the normal behaviour of calendar events is (for sure) but I believe you can edit the details after creating an event

Steps to reproduce
- Add calendar to Apple Calendars as a caldav account
- Create a new event and add an invitee
- Send the invite
- Cannot now change the title or the time/date/invites

If I create an event on an apple calendar then I am able to reopen the event and update the details. I don't know if this is a Davis thing or a Caldav thing or a sabre/dav thing. Please excuse all the things which I do not know! Any enlightenment from any one would be appreciated.

**Comment by tchapi** [comment] 2022-08-21 19:24
Thanks @JoshuaCrewe for the report. I will only have time to look into this at the beginning of September though, but I don't have this behavior on my side

**Comment by JoshuaCrewe** [comment] 2022-08-22 06:22
@tchapi knowing that you do not have this behaviour on your end is a great help and should narrow down where I need to look. Thanks for the info.

**Comment by tchapi** [comment] 2022-09-10 12:57
I've retested on the latest release, and I can change the details after having sent an invite, without problems.

I'm using the standard Calendar App on macOS Monterey. Do you still have the issue? Do you have any log, either in the calendar app, or in Davis ?

**Comment by tchapi** [comment] 2022-09-11 10:50
Closing now as I think it's not a bug in Davis but feel free to repoen if you have more info / logs / pointers

BR

**Closed by tchapi** 2022-09-11 10:50 UTC
Labels: question

**Comment by JoshuaCrewe** [comment] 2022-09-12 07:43
Thanks for taking the time to test yourself. Knowing that this is an isolated issue will be helpful. I am due to investigate this setup as well as another similar setup today so I will see if there are any error logs I can make sense of.
